version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-173-221.eu-west-1.compute.amazonaws.com
            database: da9utminaj73cb
            user: fsuyhhgohruygj
            password: c0e5d40128af31b5dfc3be6dcd8d8ca3c2cd8d510d350e7b1d8dd648ed367eeb
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true